#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'imguitest'

def options(opt):
	return

def configure(conf):
	conf.define('_WINDOWS',1)

def build(bld):
	source = [
		'main.cpp'
	]

	includes = [
		'.',
		'imgui-master'
	]

	defines = []

	libs = []

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.BINDIR

	bld.program(
		source = source,
		target = PROJECT_NAME,
		name = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines = defines,
		use = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)